### ISSUE TITLE
Promise.done is deprecated.

### ISSUE THREAD

**Issue by frNNcs** [fredkingham/django-test-runner#5] opened 2018-10-23 19:52 UTC
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
```
Promise.done (<embedded>:1692:9)
Object.runTests (C:\Users\ips\.atom\packages\django-test-runner\lib\django-test-runner.coffee:193:43)
HTMLElement.subscriptions.add.atom.commands.add.django-test-runner:run-all-tests (C:\Users\ips\.atom\packages\django-test-runner\lib\django-test-runner.coffee:41:26)
CommandRegistry.handleCommandEvent (<embedded>:24144:49)
CommandRegistry.dispatch (<embedded>:24033:23)
AtomEnvironment.dispatchApplicationMenuCommand (<embedded>:1594:25)
```

**Comment by fredkingham** [comment] 2018-10-26 17:09
This is a better written duplicate of https://github.com/fredkingham/django-test-runner/issues/2

Will try and look this weekend.

**Closed as completed by fredkingham** 2018-10-26 17:09 UTC
